name: Terraform-workflow

on: push

jobs:
  run-Terraform-workflow:
    name: 'Deploy Prod environment'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash


    steps:
    - uses: hashicorp/setup-terraform@v1
    - uses: actions/checkout@v1
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
    
    - name: Node Version
      run: node -v

    - name: Terraform Version
      run: terraform -v
      

    - name: Terraform Format
      run: terraform fmt -recursive
      working-directory: ./Terraform

    - name: Terraform init
      run: terraform init
      working-directory: ./Terraform

    - name: Terraform plan
      run: terraform plan
      working-directory: ./Terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Terraform

    - name: Terraform Apply
      run: |
        terraform apply \
          -auto-approve
      working-directory: ./Terraform


    

